# Generated by Django 4.1.4 on 2022-12-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.AddField(
            model_name='post',
            name='count',
            field=models.IntegerField(blank=True, default=0, verbose_name='count'),
        ),
    ]
